Repository ibexa/automated-translation, pull requests merged in 2024-10, with the labels that each got.

#15 IBX-7894: Added missing languages for DeepL and bumped API version to v2
  phpstan-baseline.neon
  src/bundle/DependencyInjection/IbexaAutomatedTranslationExtension.php
  src/bundle/IbexaAutomatedTranslationBundle.php
  src/bundle/Resources/config/default_settings.yaml
  src/bundle/Resources/config/field_page_services.yaml
  src/bundle/Resources/config/services.yaml
  src/lib/Client/Deepl.php
Labels: Bug, QA approved

#11 IBX-8119: Updated PHPUnit/Code style
  .github/workflows/backend-ci.yaml
  composer.json
  src/lib/Encoder.php
  tests/bundle/DependencyInjection/IbexaAutomatedTranslationExtensionTest.php
  tests/lib/Encoder/Field/RichTextFieldEncoderTest.php
  tests/lib/Encoder/Field/TextLineFieldEncoderTest.php
  tests/lib/Encoder/RichText/RichTextEncoderTest.php
  tests/lib/EncoderTest.php
Labels: Ready for review

#18 Add eztext support
  src/bundle/Resources/config/services.yaml
  src/lib/Encoder/Field/TextBlockFieldEncoder.php
  tests/lib/Encoder/Field/TextBlockFieldEncoderTest.php
Labels: QA approved
